"use client";
import { useEffect, useReducer, useRef, useState } from "react";
import { usePathname, useRouter } from "next/navigation";
import { hydrateTourState, initialTourState, routeMatches, TOUR_STORAGE_KEY, tourReducer, type TourStep } from "@/lib/guided-tour";

const copy: Record<Exclude<TourStep, "complete">, { title: string; body: string; target?: string; next?: string }> = {
  dashboard: { title: "Your operations hub", body: "Start with pipeline, revenue, and build signals. Open Clients to follow an intake.", target: "nav-clients" },
  clients: { title: "Client intake", body: "CRM records keep intake, source data, and lead scoring together.", next: "Continue to Builds" },
  builds: { title: "Build estimator", body: "A build turns project choices into deterministic pricing. Open Builds to see it.", target: "nav-builds" },
  newBuild: { title: "Build estimator", body: "Create a build to open the deterministic quote tool.", target: "new-build-action" },
  estimator: { title: "Explore the estimator", body: "Adjust the estimator freely; this guided path never modifies your work.", next: "Continue to Proposals" },
  proposalNav: { title: "Continue to proposals", body: "When you are ready, use the Proposals tab to turn an estimate into a customer story.", target: "nav-proposals" },
  proposals: { title: "Customer-ready proposal", body: "Proposals turn a selected estimate into a clear narrative and payment plan.", next: "Open Hayward preview" },
  template: { title: "Preview mode", body: "The deterministic preview keeps the editing sidebar available.", target: "nav-contracts" },
  contracts: { title: "Auditable contracts", body: "Contracts carry project records, acknowledgements, signatures, and audit evidence.", next: "Open signed Hayward contract" },
  contract: { title: "Signed record", body: "This final callout shows the immutable signed document and its audit evidence.", next: "Finish tour" },
};
const go = (step: TourStep) => step === "dashboard" ? "/" : step === "clients" || step === "builds" ? "/clients" : step === "newBuild" ? "/builds" : step === "estimator" || step === "proposalNav" ? "/builds/new" : step === "proposals" ? "/proposals" : "/contracts";

export function GuidedTourProvider({ enabled, children }: { enabled: boolean; children: React.ReactNode }) {
  const pathname = usePathname(), router = useRouter();
  const [state, dispatch] = useReducer(tourReducer, initialTourState), [ready, setReady] = useState(false), [box, setBox] = useState<DOMRect | null>(null);
  const dialog = useRef<HTMLDivElement>(null), previous = useRef<HTMLElement | null>(null);
  useEffect(() => { if (!enabled) return; try { const saved=hydrateTourState(JSON.parse(localStorage.getItem(TOUR_STORAGE_KEY) || "null")); if(saved) dispatch({ type: "HYDRATE", state: saved }); } catch {} setReady(true); }, [enabled]);
  useEffect(() => { if (enabled && ready) localStorage.setItem(TOUR_STORAGE_KEY, JSON.stringify(state)); }, [enabled, ready, state]);
  useEffect(() => { if (enabled && ready && state.active) dispatch({ type: routeMatches(state.step, pathname) ? "RESUME" : "PAUSE" }); }, [enabled, pathname, ready, state.active, state.step]);
  useEffect(() => { if (!enabled || !ready || !state.active || state.paused) return; previous.current ??= document.activeElement as HTMLElement; const target = copy[state.step as Exclude<TourStep,"complete">]?.target; let tries = 0; const measure = () => { const candidates=target?Array.from(document.querySelectorAll(`[data-tour="${target}"]`)) as HTMLElement[]:[]; const el=candidates.find(candidate=>candidate.getClientRects().length>0&&getComputedStyle(candidate).visibility!=="hidden")||null; if (el) setBox(el.getBoundingClientRect()); else if (++tries < 9) window.setTimeout(measure, 150); else setBox(null); }; measure(); dialog.current?.focus(); window.addEventListener("resize", measure); return () => window.removeEventListener("resize", measure); }, [enabled, ready, state.active, state.paused, state.step, pathname]);
  useEffect(() => () => previous.current?.focus(), []);
  if (!enabled || !ready) return <>{children}</>;
  if (!state.active) return <>{children}<button onClick={() => { dispatch({ type: "RESTART" }); router.push("/"); }} className="fixed bottom-3 right-3 z-30 rounded bg-background/95 px-3 py-2 text-xs shadow print:hidden">Restart tour</button></>;
  const item = copy[state.step as Exclude<TourStep, "complete">]; const ordinal = ["dashboard","clients","builds","newBuild","estimator","proposalNav","proposals","template","contracts","contract"].indexOf(state.step) + 1;
  const next = () => { if (state.step === "clients" || state.step === "estimator") dispatch({ type: "NEXT" }); else if (state.step === "proposals") { dispatch({ type: "NEXT" }); router.push("/proposals?tourPreview=1"); } else if (state.step === "contracts") { dispatch({ type: "NEXT" }); router.push("/contracts?tourSigned=1"); } else dispatch({ type: "NEXT" }); };
  const activate = () => { if (item.target === "nav-clients") { dispatch({ type: "NEXT" }); router.push("/clients"); } else if (item.target === "nav-builds") { dispatch({ type: "NEXT" }); router.push("/builds"); } else if (item.target === "new-build-action") { dispatch({ type: "NEXT" }); router.push("/builds/new"); } else if (item.target === "nav-proposals") { dispatch({ type: "NEXT" }); router.push("/proposals"); } else if (item.target === "nav-contracts") { dispatch({ type: "NEXT" }); router.push("/contracts"); } };
  const freeplay=state.step==="estimator"; const close=(action:"SKIP"|"RESTART")=>{dispatch({type:action});previous.current?.focus();if(action==="RESTART")router.push("/")}; const trap=(event:React.KeyboardEvent<HTMLDivElement>)=>{if(freeplay||event.key!=="Tab")return;const controls=Array.from(event.currentTarget.querySelectorAll<HTMLElement>('button,[href],[tabindex]:not([tabindex="-1"])')).filter(x=>!x.hasAttribute("disabled"));if(!controls.length)return;const first=controls[0],last=controls[controls.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}}; return <>{children}{!freeplay&&<div aria-hidden className="fixed inset-0 z-40 bg-black/45" />}{box && item.target && <button aria-label={`Open ${item.title}`} onClick={activate} className="fixed z-40 rounded-lg ring-4 ring-cyan-300/90 shadow-[0_0_34px_rgba(103,232,249,.8)] motion-reduce:shadow-none" style={{ left: box.left - 4, top: box.top - 4, width: box.width + 8, height: box.height + 8 }} />}<div ref={dialog} onKeyDown={trap} tabIndex={-1} role={freeplay?"status":"dialog"} aria-modal={!freeplay} aria-live="polite" aria-label={`Guided tour: ${item.title}`} className="fixed bottom-4 right-4 z-50 max-w-sm rounded-xl border bg-background p-4 shadow-2xl outline-none"><p className="text-xs font-semibold uppercase tracking-wide text-primary">Guided tour · {ordinal} / 10</p><h2 className="mt-1 font-semibold">{item.title}</h2><p className="mt-1 text-sm text-muted-foreground">{item.body}</p>{state.paused && <button onClick={() => router.push(go(state.step))} className="mt-3 rounded border px-3 py-2 text-xs">Return to tour</button>}<div className="mt-4 flex gap-2"><button onClick={item.target?activate:next} className="rounded bg-primary px-3 py-2 text-xs font-medium text-primary-foreground">{item.target?"Open highlighted step":item.next || "Continue"}</button><button onClick={() => close("SKIP")} className="ml-auto text-xs underline">Skip</button><button onClick={() => close("RESTART")} className="text-xs underline">Restart</button></div></div></>;
}
