"use client";
import { normalizeContractData, type ContractEnvelope, type ContractFields } from "@/lib/contract-document";
const money=(v:unknown)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(Number(v)||0);
const label=(key:string)=>key.replace(/([A-Z])/g," $1").replace(/^./,x=>x.toUpperCase());
export function ContractDocument({ data, editable=false, onChange, signature }: { data: unknown; editable?: boolean; onChange?: (fields: ContractFields)=>void; signature?: { signerName?:string; signerEmail?:string; signerIp?:string; signedTimestamp?:string; consentTimestamp?:string; consent?:boolean; auditTrail?:unknown[]; documentHash?:string } | null }) {
 const document: ContractEnvelope=normalizeContractData(typeof data==="string"?JSON.parse(data):data), f=document.fields;
 const set=(key:string,value:string|boolean)=>onChange?.({...f,[key]:value});
 const sections=[[["installationAddress","billingAddress","legalDescr","subdivision","jobPhone","others"],["Project and site"]],[["earthRemovalYes","additionalFillBuyer","additionalFillContractor","shuttleDigYes","spotSurveyYes","safetyCode"],["Earthwork and safety"]],[["poolShape","poolSize","dimensionsLength","dimensionsWidth","sqFt","minDepth","maxDepth"],["Pool structure"]],[["interiorQuartz","interiorPebble","interiorColor","interiorOther","copingBNBR","copingPrecast","copingTrav","copingCantil","tileAllowance"],["Interior, coping, and tile"]],[["vacLineYes","skimmerCount","filterSize","filterCartridge","filterDE","pumpHP","addlPumpHP"],["Plumbing and filtration"]],[["light100w","light300w","ledLightCount","ledLightYes","cleaningEquipment","testKit"],["Lighting and cleaning"]],[["chlorinatorYes","saltSystemYes","infloorCleanYes","maintenanceFree"],["Water treatment"]],[["benchDeepEnd","benchShallow","sunShelf","handRailYes","ladderYes"],["Pool features"]],[["automation","timeClock","controlsJandy","controlsAqualogic","autoFillMech","autoFillElectronic"],["Automation and autofill"]],[["pilingsConcrete","pilingsHelicalYes","pilingsDrivenBy","pilingsCappedBy","engineering"],["Engineering and pilings"]],[["heaterHeatPump","heaterHeatPumpSize","heaterGas","heaterGasSize","heaterSolar","heaterTankHookup"],["Heat"]],[["spaDim","spaElev","spaLight","jets","airBlowerHP","spaCoping"],["Spa"]],[["deckMaterial","deckType","deckColor","deckPattern","deckLanai","deckSkimcoat","poolWiringYes"],["Decking and wiring"]],[["screenType","screenColor","screenDoors","screenGutters","screenPanroof","screenRailing","screenFence"],["Screen enclosure"]],[["sprinklersContractor","sprinklersBuyer","sodContractor","sodBuyer","spotSurveyBuyer","alarms"],["Irrigation, sod, and allowances"]],[["meshBarrierContractor","meshBarrierBuyer","item38","item39","item40","proposedBy"],["Additional items"]]] as const;
 return <article className="contract-document mx-auto max-w-4xl bg-white p-6 text-slate-900 shadow-sm print:max-w-none print:p-0">
  <header className="border-b-4 border-cyan-800 pb-5"><p className="text-xs font-semibold uppercase tracking-[.2em] text-cyan-800">Persistent Pools, LLC · Contractor</p><h1 className="mt-1 text-3xl font-bold">Construction Contract</h1><p className="mt-2 text-xs text-slate-600">Fictional portfolio demonstration. Compliance-ready presentation only; not a binding agreement or legal advice.</p></header>
  <section className="grid gap-3 py-5 sm:grid-cols-2">{["contractDate","purchasedBy","installationAddress","billingAddress","jobPhone","contractPrice"].map(key=><label key={key} className="text-xs font-semibold uppercase tracking-wide text-slate-500">{label(key)}{editable?<input value={String(f[key]??"")} onChange={e=>set(key,e.target.value)} className="mt-1 w-full border-b border-slate-300 p-1 text-base font-normal text-slate-900"/>:<span className="mt-1 block text-base font-normal normal-case text-slate-900">{key==="contractPrice"?money(f[key]):String(f[key]??"—")}</span>}</label>)}</section>
  <section className="grid gap-4 border-y py-5 sm:grid-cols-2">{sections.map(([keys,[title]])=><div key={title} className="break-inside-avoid rounded border p-3"><h2 className="font-semibold">{title}</h2>{keys.map(key=><div key={key} className="mt-2 text-sm"><span className="text-slate-500">{label(key)}: </span>{typeof f[key]==="boolean"?<input aria-label={label(key)} type="checkbox" checked={Boolean(f[key])} disabled={!editable} onChange={event=>set(key,event.target.checked)}/>:editable?<input value={String(f[key]??"")} onChange={e=>set(key,e.target.value)} className="border-b border-slate-300"/>:<span>{String(f[key]??"—")}</span>}</div>)}</div>)}</section>
  <section className="break-inside-avoid py-5"><h2 className="text-lg font-semibold">Six milestone payments</h2><div className="mt-2 overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left"><th className="p-2">Milestone</th><th className="p-2 text-right">Percent</th><th className="p-2 text-right">Amount</th></tr></thead><tbody>{[1,2,3,4,5,6].map(n=><tr key={n} className="border-b"><td className="p-2">{String(f[`payment${n}Name`]??"")}</td><td className="p-2 text-right">{String(f[`payment${n}Percentage`]??0)}%</td><td className="p-2 text-right">{money(f[`payment${n}Amount`])}</td></tr>)}</tbody></table></div></section>
  <section className="break-inside-avoid py-5"><h2 className="text-lg font-semibold">Terms and conditions</h2>{document.terms.map(term=><div key={term.title} className="mt-3"><h3 className="font-medium">{term.title}</h3><p className="text-sm leading-6 text-slate-700">{term.body}</p></div>)}</section>
  <section className="break-inside-avoid py-5"><h2 className="text-lg font-semibold">Acknowledgements</h2>{document.acknowledgements.map(a=><div key={a.number} className="mt-2 grid grid-cols-[1fr_auto_auto] gap-2 border-b py-2 text-xs"><span><b>{a.number}. {a.title}</b> — {a.text}</span><span>Contractor: {a.contractorInitials || "—"}</span><span>Customer: {a.customerInitials || "—"}</span></div>)}</section>
  <footer className="grid gap-5 border-t pt-5 sm:grid-cols-2"><div><p className="text-xs text-slate-500">Contractor signature</p><p className="mt-5 border-b pb-1">{String(f.contractorSignature??"Persistent Pools, LLC")}</p></div><div><p className="text-xs text-slate-500">Customer signature</p><p className="mt-5 border-b pb-1">{signature?.signerName ?? String(f.buyerSignature1??"")}</p></div>{signature&&<p className="col-span-full text-xs text-slate-500">Signed {signature.signedTimestamp} · {signature.signerEmail} · IP {signature.signerIp} · consent {String(signature.consent)} · audit events {signature.auditTrail?.length??0} · hash {signature.documentHash}</p>}</footer>
 </article>;
}
